### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by mateosantosdev** [volure/keystoreBrute#2]
Hi,

Ive tried your program, its a great idea. Unfortunately it doesnt work for me.

It always say that cannot find the file. Ive checked and rechecked the path to my .keystore and its fine.

Do you know what is the problem ?

Im executing: bin/Debug/keystoreBrute.exe

Thanks!

**Comment by volure** [comment]
I couldnt know what the problem is. You would have to give some more detail, maybe post some error code.

**Comment by allisterf** [comment]
I'm having exactly  the same problem. I took a screen shot of the page. Do you have an email address I can send it to for you to have a look?
Allister

**Comment by allisterf** [comment]
Found your email address - have mailed you a screenshot...
Allister

**Comment by volure** [comment]
ok. it appears that the reason you were having this problem is that you were using the application that was compiled on my machine. Unfortunately that application had my keystore hardcoded in. And the code has since changed. 

Now the application allows you to specify the keystore location in a text box. I did not intend people to just use the compiled version however I guess if its included it should probably work. 

I have recompiled it and hopefully that helps :)

**Comment by volure** [comment]
Let me know if this issue is not resolved 

Thanks :)

**Comment by allisterf** [comment]
OK - not sure I still quite have this right.

I've downloaded whatever the current version (from today) is on github and
have run the exe file which is in the bin directory. There is a text box -
as there was in the previous version I was using - to enter the file and
its path for the keystore to be put through the wrangler.

However, I'm still getting the file not found error (screen capture
attached).

allister

---

## 

Allister Fugill

My email address is changing shortly from allister.fugill@uk.om.org to

## allister.fugill@om.org. Please amend your address book

On 02/01/2012 09:15, "Volure DarkAngel"
<reply+i-2549140-5d9a937a7ebb70727b7f8cdb26d3ab89d35e9203-1244015@reply.git
hub.com> wrote:

> ok. it appears that the reason you were having this problem is that you
> were using the application that was compiled on my machine. Unfortunately
> that application had my keystore hardcoded in. And the code has since
> changed.
> 
> Now the application allows you to specify the keystore location in a text
> box. I did not intend people to just use the compiled version however I
> guess if its included it should probably work.
> 
> I have recompiled it and hopefully that helps :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/volure/keystoreBrute/issues/2#issuecomment-3328236

  Operation Mobilisation (OM) - a company limited by guarantee - The Quinta, Weston Rhyn, Oswestry, SY10 7LT, United Kingdom
  Company reg no: 2564320 (England & Wales) - Charity reg. no: 1008196 (England & Wales) - SC040988 (Scotland)
  Web: http://www.uk.om.org

**Comment by volure** [comment]
I did not get the screen capture, Can you send the email to volure@loki-systems.com

**Comment by volure** [comment]
Can you send the error details?

**Comment by volure** [comment]
Open a command line and type

echo $PATH

Check if keytool is in your path

**Comment by volure** [comment]
sorry. If you are on windows, you will need to execute 

echo %PATH%

Check "Those" directories to see if keytool is in the path.

Sorry for the mixup :)

**Comment by allisterf** [comment]
No there doesn't seem to be keytool installed.

I'm actually working on a mac using eclipse to generate the keystore. I
have vmware to run a windows partition and was trying to get you programme
to work there. I assume you don't have a mac version at all?

allister

---

## 

Allister Fugill

My email address is changing shortly from allister.fugill@uk.om.org to

## allister.fugill@om.org. Please amend your address book

On 02/01/2012 18:05, "Volure DarkAngel"
<reply+i-2549140-5d9a937a7ebb70727b7f8cdb26d3ab89d35e9203-1244015@reply.git
hub.com> wrote:

> sorry. If you are on windows, you will need to execute
> 
> echo %PATH%
> 
> Check "Those" directories to see if keytool is in the path.
> 
> Sorry for the mixup :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/volure/keystoreBrute/issues/2#issuecomment-3331976

  Operation Mobilisation (OM) - a company limited by guarantee - The Quinta, Weston Rhyn, Oswestry, SY10 7LT, United Kingdom
  Company reg no: 2564320 (England & Wales) - Charity reg. no: 1008196 (England & Wales) - SC040988 (Scotland)
  Web: http://www.uk.om.org

**Comment by volure** [comment]
ok. this application runs on mac. Check out Mono. and Monodevelop.

I wrote the application on windows, but I recompiled it this last time in monodevelop.

http://www.go-mono.com/mono-downloads/download.html
http://monodevelop.com/Download

Download the SDK and the Monodevelop app.
then from the command line you can run

mono keystoreBrute.exe

and you can open the project in monodevelop.

the mac is where 'echo $PATH' came from.....

Hope that helps :)

**Comment by volure** [comment]
Did this work out for you ?
